# Generated by Django 2.1.7 on 2019-04-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190401_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-created',), 'verbose_name': '版块', 'verbose_name_plural': '版块'},
        ),
        migrations.AddField(
            model_name='post',
            name='src_url',
            field=models.URLField(blank=True, null=True, verbose_name='原文链接(可选)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/post/cover/', verbose_name='封面图(可选)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_posts', to='posts.Topic', verbose_name='所属版块(可选)'),
        ),
    ]
