# Generated by Django 2.1.7 on 2019-04-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190402_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/post/cover/', verbose_name='封面图(可选项)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='src_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='原文链接(可选项)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_posts', to='posts.Topic', verbose_name='所属版块(可选项)'),
        ),
    ]
