# Generated by Django 2.0 on 2021-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='absolute_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片链接'),
        ),
    ]
