# Generated by Django 2.1.7 on 2019-03-31 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190331_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
